### ISSUE TITLE
Feature Request: Sourcing Playlists as input for Sync to Device

### ISSUE THREAD

**Issue by speakn2pabst** [Tamriel/quod_libet_sync_to_device#3]
I have a great new idea, if the plugin could use playlists as input for sync operations along with the current search results.  

It'd be great for newer users of Quod Libet or users who traffic more with playlists rather then procedural searches.

Thanks for your consideration!

**Comment by Tamriel** [comment]
Ok, I see you want this.
I will look what I can do ;-)

**Comment by speakn2pabst** [comment]
Many thanks!

**Comment by Tamriel** [comment]
I just found out that this already exists. It is the plugin 'export playlist to folder'.
